%Code automatically generated by genRunDemos.
%Run BLT demos.

linregDist.demoPolyFitNoErrorBars();
linregDist.demoPolyFitErrorBars();
linregDist.demoGaussVsNIG();
linregDist.demoBasisSparse();
linregDist.demoBasisDense();
linregDist.demoBasis();
linregDist.demoBasisSimple();
linregDist.demoRbf();
linregDist.demoPolyFitRidgeBIC();
linregDist.demoPolyFitRidgeCV();
pause(2)
close all
clear all

linregDist.demoPolyFitN();
linregDist.demoPolyFitRidgeU();
linregDist.demoPolyFitRidge();
linregDist.demoPolyFitDegree();

logregDist.demoOptimizer();
logregDist.demoLaplaceGirolami();
logregDist.demoSat();
multinomLogregDist.demoOptimizer();
multinomLogregDist.demoCrabs();
ggm.demoInfer();
pause(2)
close all
clear all

ggm.demoBIC();
ggm.demo();
ggmDecomposable.demoPostModelsExhaustive();
chordalGraph.demo();
graph.demo();
mcmcInfer.demoProposalGmm();
mcmcInfer.demoGmmBurnin();
mcmcInfer.demoConvDiagGmm();
mvnMcmcInfer.demo2d();
mvnMcmcInfer.demo();
pause(2)
close all
clear all

tabularFactor.demoSprinkler2();
tabularFactor.demoSprinkler();
bernoulliDist.demoBayesianUpdatingDiscretePrior();
bernoulliDist.demoSeqUpdate();
betaBinomDist.demoEbCancer();
betaDist.demoPlot();
binomDist.demoPostPred();
binomDist.demoPost();
binomDist.demoPlot();
dirichletDist.demoPlotHisto();
pause(2)
close all
clear all

dirichletDist.demoPlot3d();
gammaDist.demoRainfall();
gammaDist.demoPlot();
gaussDist.demoCV();
gaussDist.demoHeightWeight();
gaussDist.demoPlot();
gaussMixDist.demoPlot();
hiwDist.demo();
invGammaDist.demoSample();
invGammaDist.demoPlot();
pause(2)
close all
clear all

invWishartDist.demoPlot1d();
invWishartDist.demoPlot2d();
laplaceDist.demoPlot();
multinomDist.demoPlot();
mvnDist.demoImputation();
mvnDist.demoHeightWeight();
mvnDist.demoPlot2d();
mvnDist.demoPlot2dMarginals();
mvnDist.demoCondition2d();
mvnDist.demoCondition();
pause(2)
close all
clear all

mvnDist.demoInferParamsMean1d();
mvnDist.demoInferParamsMean2d();
mvnDist.demoInferParamsSigma2d();
mvnDist.demoSeqUpdateMu1d();
mvnDist.demoSeqUpdateSigma1d();
mvnDist.demoInferParamsMuSigma1dPriors();
mvnDist.demoSeqUpdateMuSigma1d();
mvnDist.demoSoftCondition();
mvnInvWishartDist.demoPlot();
mvtDist.demoPlot2dStudentVsGaussian();
pause(2)
close all
clear all

poissonDist.demoPlot();
sampleDist.demo();
studentDist.demoStudentVsGaussianRobustnessToOutliers();
studentDist.demoPlotStudentVsGaussian();
tabularDist.demoSprinkler();
wishartDist.demoPlot2d();
chainTransformer.demo();
demoChangeOfVars;
pause(2)
close all
clear all


