%Code automatically generated by genRunDemos.
%Run BLT demos.
linregDist.demoPolyFitNoErrorBars();
linregDist.demoPolyFitErrorBars();
linregDist.demoGaussVsNIG();
linregDist.demoBasisSparse();
linregDist.demoBasisDense();
linregDist.demoBasis();
linregDist.demoBasisSimple();
linregDist.demoRbf();
linregDist.demoPolyFitRidgeBIC();
linregDist.demoPolyFitRidgeCV();
pause(2)
close all
clear all

linregDist.demoPolyFitN();
linregDist.demoPolyFitRidgeU();
linregDist.demoPolyFitRidge();
linregDist.demoPolyFitDegree();
logregDist.demoOptimizer2();
logregDist.demoLaplaceGirolami();
logregDist.demoSat();
logregDist.demoVisualizePredictive();
logregDist.demoOptimizer();
logregDist.demoCrabs();
pause(2)
close all
clear all

ggm.demoInfer();
ggm.demoBIC();
ggm.demo();
ggmDecomposable.demoPostModelsExhaustive();
chordalGraph.demo();
graph.demo();
mcmcInfer.demoProposalGmm();
mcmcInfer.demoGmmBurnin();
mcmcInfer.demoConvDiagGmm();
mvnMcmcInfer.demo2d();
pause(2)
close all
clear all

mvnMcmcInfer.demo();
tabularFactor.demoSprinkler2();
tabularFactor.demoSprinkler();
crossValidation.demo();
bernoulliDist.demoBayesianUpdatingDiscretePrior();
bernoulliDist.demoSeqUpdate();
betaBinomDist.demoEbCancer();
betaDist.demoPlot();
binomDist.demoPostPred();
binomDist.demoPost();
pause(2)
close all
clear all

binomDist.demoPlot();
dirichletDist.demoPlotHisto();
dirichletDist.demoPlot3d();
gammaDist.demoRainfall();
gammaDist.demoPlot();
gaussDist.demoCV();
gaussDist.demoHeightWeight();
gaussDist.demoPlot();
gaussMixDist.demoPlot();
hiwDist.demo();
pause(2)
close all
clear all

invGammaDist.demoSample();
invGammaDist.demoPlot();
invWishartDist.demoPlot1d();
invWishartDist.demoPlot2d();
laplaceDist.demoPlot();
multinomDist.demoPlot();
mvnDist.demoImputation();
mvnDist.demoHeightWeight();
mvnDist.demoPlot2d();
mvnDist.demoPlot2dMarginals();
pause(2)
close all
clear all

mvnDist.demoCondition2d();
mvnDist.demoCondition();
mvnDist.demoInferParamsMean1d();
mvnDist.demoInferParamsMean2d();
mvnDist.demoInferParamsSigma2d();
mvnDist.demoSeqUpdateMu1d();
mvnDist.demoSeqUpdateSigma1d();
mvnDist.demoInferParamsMuSigma1dPriors();
mvnDist.demoSeqUpdateMuSigma1d();
mvnDist.demoSoftCondition();
pause(2)
close all
clear all

mvnInvWishartDist.demoPlot();
mvtDist.demoPlot2dStudentVsGaussian();
poissonDist.demoPlot();
sampleDist.demo();
studentDist.demoStudentVsGaussianRobustnessToOutliers();
studentDist.demoPlotStudentVsGaussian();
tabularDist.demoSprinkler();
wishartDist.demoPlot2d();
chainTransformer.demo();
demoChangeOfVars;
pause(2)
close all
clear all

pause(2)
close all
clear all


